apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-management-service
  labels:
    app: restaurant-management-service
spec:
  replicas: 2 # Number of pods
  selector:
    matchLabels:
      app: restaurant-management-service
  template:
    metadata:
      labels:
        app: restaurant-management-service
    spec:
      containers:
        - name: restaurant-management-service
          image: gcr.io/mtogov1/restaurant-management-service:latest # Replace with your Docker image name
          ports:
            - containerPort: 8080 # Update to match the application's listening port
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production # Example environment variable
